### ISSUE TITLE
How to implement callback to haxe?

### ISSUE THREAD

**Issue by kevinresol** [snowkit/linc#6]
I am writing some native extension for android. I am able to use `SDL_AndroidGetJNIEnv` to grab the JNIEvn for the JNI stuffs. The Java library I am using has callback delegate that is used to notify user code when some events happened. I tried to pass a haxe function into linc, so that the delegate will be able to invoke a haxe function through JNI.

``` haxe
// haxe
@:native('linc::empty::setupCallback')
static function setupCallback(cb:Int->Void):Void;
```

``` cpp
// c++
void setupCallback(Dynamic cb);
```

Then in the cpp body of `setupCallback`, I tried to call `cb(1);` and it does invoke in the haxe side. But if I try to invoke `cb(1)` in the Java delegate, it failed. (I registered a delegate in java code, which will in turn call a JNI method in cpp, and in that cpp JNI method I call `cb(1)`). 

The error is something like this:
`Fatal signal 11 (SIGSEGV), code 1, fault addr 0x24`

I am not expert of cpp. Is the error caused by a threading issue, because the Java delegate invocation is not in the same thread where Haxe is running? Or is it because `cb` has been garbage collected between the time of `setupCallback` and the java delegate call?

I am been struggling for some time about this. Any help is appreciated. Thanks.

**Comment by ruby0x1** [comment]
I've found the most straight forward way to deal with all of the complexity (GC, threads, etc) is to start by keeping all of the user callback (and user callback data) on the Haxe side. 

Then instead of passing the user code to the native side, you instead pass a single wrapper internal function, using `cpp.Callable.fromStaticFunction`, which on the cpp side for your function is `::cpp::Function < Void(int) >;` . You can make a typedef on the c++ for clarity, `typedef ::cpp::Function < Void(int) > InternalCallbackFN;` and use `InternalCallbackFN` as a type.

So your setupCallback on the cpp side now refers to the cpp::Function via the typedef:
`extern void setupCallback( InternalCallbackFN internal_fn );`

Now you can store `internal_fn`, and call it like a regular function. It can be tested for `if(internal_fn == null())` like other haxe types on c++ side.

On the haxe side, when the internal function gets called, you call the user function from regular haxe code.

On android specifically, because there are places where android itself or SDL may call functions from other threads, it's important to let hxcpp know what is happening. Hugh has implemented a helper in NME that I use in [linc_sdl](https://github.com/snowkit/linc_sdl/blob/master/linc/linc_sdl.h#L117-L139) which you can see there and [used here](https://github.com/snowkit/linc_sdl/blob/master/linc/linc_sdl.cpp#L722-L734).

There are a few callbacks in linc_sdl that are handled in this way. [This class](https://github.com/snowkit/linc_sdl/blob/master/sdl/SDL.hx#L1258) holds the user callbacks and calls into the native side. You will notice that the callbacks are just given a simple int ID, and on the c++ side this int is given to SDL, so that it's easy to work out _which_ timer is being called for instance.

There are a few steps with this approach but I prefer it because this allows the user function to be _any_ haxe function, like anonymous functions, member functions, static functions are all fine - because it's just regular haxe. It also means that the user data can be complex, without having to try and coerce that to java or cpp side, or worry about GC. By using the cpp.Callable stuff it makes it simpler for hxcpp to track the lifetimes and not GC your functions as well, so there is no chance of the function being collected.

There are a few examples there already, so hopefully you can wrap your head around what is happening there - starting simple is a good idea. Hope that helps!

Oh and as for sigsev, you probably want to make sure you're doing a debug build and that your logcat isn't filtered, ART debugging is enabled, JNICheck is enabled, and other native debugging flags are set so that you can see the callstack.

**Comment by kevinresol** [comment]
Thanks for the detailed explanation! I will give it a try and report back.

**Comment by kevinresol** [comment]
It turns out that it is working very well with cpp.Callable. So I am closing this now. Thanks again!
